UPDATE REG_LOG SET REG_PATH = REPLACE(REG_PATH, ':', '-at-') WHERE REG_PATH LIKE '%:%';
UPDATE REG_PATH SET REG_PATH_VALUE = REPLACE(REG_PATH_VALUE, ':', '-at-') WHERE REG_PATH_VALUE LIKE '%:%';
UPDATE REG_PROPERTY SET REG_VALUE = REPLACE(REG_VALUE, ':', '-at-') WHERE REG_VALUE LIKE '%:%';
UPDATE REG_RESOURCE SET REG_NAME = REPLACE(REG_NAME, ':', '-at-') WHERE REG_NAME LIKE '%:%';
UPDATE REG_RESOURCE_HISTORY SET REG_NAME = REPLACE(REG_NAME, ':', '-at-') WHERE REG_NAME LIKE '%:%';
UPDATE REG_SNAPSHOT SET REG_RESOURCE_NAME = REPLACE(REG_RESOURCE_NAME, ':', '-at-') WHERE REG_RESOURCE_NAME LIKE '%:%';
UPDATE REG_ASSOCIATION SET REG_SOURCEPATH = REPLACE(REG_SOURCEPATH, ':', '-at-'), REG_TARGETPATH = REPLACE(REG_TARGETPATH, ':', '-at-') WHERE REG_SOURCEPATH LIKE '%:%' OR REG_TARGETPATH LIKE '%:%';