UPDATE UM_PERMISSION SET UM_RESOURCE_ID = REPLACE(UM_RESOURCE_ID, ':', '-at-') WHERE UM_RESOURCE_ID LIKE '%:%';
UPDATE UM_HYBRID_ROLE SET UM_ROLE_NAME = REPLACE(UM_ROLE_NAME, ':', '-at-') WHERE UM_ROLE_NAME LIKE '%:%';
UPDATE UM_ROLE_PERMISSION SET UM_ROLE_NAME = REPLACE(UM_ROLE_NAME, ':', '-at-') WHERE UM_ROLE_NAME LIKE '%:%';