/*
 * Copyright (c) 2005-2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.social.db.adapter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public interface AdapterInterface {
	
	/**
	 * Get paginated activity ResultSet.
	 * 
	 * @param connection
	 * @param targetId
	 * @param tenant
	 * @param order
	 * @param limit
	 * @param offset
	 * @return activity ResultSet
	 * @throws SQLException 
	 */
	ResultSet getPaginatedActivitySet(Connection connection,
			String targetId, String tenant, String order, int limit, int offset) throws SQLException;
	
	/**
	 * Get paginated popular target ResultSet.
	 * 
	 * @param connection
	 * @param type
	 * @param tenant
	 * @param limit
	 * @param offset
	 * @return popular target ResultSet
	 * @throws SQLException 
	 */
	ResultSet getPopularTargetSet(Connection connection,
			String type, String tenantDomain, int limit, int offset)
			throws SQLException;
	
	/**
	 * Insert comment activity.
	 * 
	 * @param connection
	 * @param json object
	 * @param targetId
	 * @param userId
	 * @param tenantDomain
	 * @param totalLikes
	 * @param totalUnlikes
	 * @param timeStamp
	 * @return long generated ID
	 * @throws SQLException 
	 */
	long insertCommentActivity(Connection connection,
			String json, String targetId, String userId, String tenantDomain,
			int totalLikes, int totalUnlikes, int timeStamp)
			throws SQLException;

	/**
	 * Insert rating activity.
	 * 
	 * @param connection
	 * @param autoGeneratedKey
	 * @param targetId
	 * @param userId
	 * @param tenantDomain
	 * @param rating
	 * @param timeStamp
	 * @return boolean
	 * @throws SQLException 
	 */
	boolean insertRatingActivity(Connection connection,
			long autoGeneratedKey, String targetId, String userId,
			String tenantDomain, int rating, int timeStamp) throws SQLException;

	/**
	 * Insert like activity.
	 * 
	 * @param connection
	 * @param targetId
	 * @param userId
	 * @param tenantDomain
	 * @param likeValue
	 * @param timeStamp
	 * @return boolean
	 * @throws SQLException 
	 */
	boolean insertLikeActivity(Connection connection,
			String targetId, String actor, String tenantDomain, int likeValue,
			int timestamp) throws SQLException;

	/**
	 * Get paginated activity prepared statement.
	 * 
	 * @param connection
	 * @param targetId
	 * @param tenant
	 * @param order
	 * @param limit
	 * @param offset
	 * @return PreparedStatement
	 * @throws SQLException 
	 */
	PreparedStatement getPaginatedActivitySetPreparedStatement(
			Connection connection, String targetId, String tenant,
			String order, int limit, int offset) throws SQLException;

	/**
	 * Get popular target prepared statement.
	 * 
	 * @param connection
	 * @param type
	 * @param tenant
	 * @param limit
	 * @param offset
	 * @return PreparedStatement
	 * @throws SQLException 
	 */
	PreparedStatement getPopularTargetSetPreparedStatement(
			Connection connection, String type, String tenantDomain, int limit,
			int offset) throws SQLException;

	/**
	 * Get comment activity insert prepared statement.
	 * 
	 * @param connection
	 * @param json
	 * @param targetId
	 * @param userId
	 * @param tenant
	 * @param totalLikes
	 * @param totalUnlikes
	 * @param timeStamp
	 * @return PreparedStatement
	 * @throws SQLException 
	 */
	PreparedStatement getInsertCommentActivityPreparedStatement(
			Connection connection, String json, String targetId, String userId,
			String tenantDomain, int totalLikes, int totalUnlikes, int timeStamp)
			throws SQLException;

	/**
	 * Get rating activity insert prepared statement.
	 * 
	 * @param connection
	 * @param autoGeneratedKey
	 * @param targetId
	 * @param userId
	 * @param tenant
	 * @param rating
	 * @param timeStamp
	 * @return PreparedStatement
	 * @throws SQLException 
	 */
	PreparedStatement getinsertRatingActivityPreparedStatement(
			Connection connection, long autoGeneratedKey, String targetId,
			String userId, String tenantDomain, int rating, int timeStamp)
			throws SQLException;

	/**
	 * Get like activity insert prepared statement.
	 * 
	 * @param connection
	 * @param targetId
	 * @param userId
	 * @param tenant
	 * @param likeValue
	 * @param timeStamp
	 * @return PreparedStatement
	 * @throws SQLException 
	 */
	PreparedStatement getinsertLikeActivityPreparedStatement(
			Connection connection, String targetId, String actor,
			String tenantDomain, int likeValue, int timestamp)
			throws SQLException;

	/**
	 * Get generated ID by providing the resultSet.
	 * 
	 * @param generatedKeys
	 * @return generated ID
	 * @throws SQLException 
	 */
	long getGenaratedKeys(ResultSet generatedKeys) throws SQLException;

}
